name: Test

on:
  pull_request:
    types: [ opened ]

jobs:
  test:
    runs-on: ubuntu-latest 
    permissions:
      issues: write

    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



  
